# Generated by Django 4.1.5 on 2023-01-29 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathsiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.CharField(choices=[('B', 'Beginer'), ('A', 'Advanced'), ('M', 'Master'), ('GM', 'GrandMaster')], default='B', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='mathsite_users', to='auth.group')),
            ],
            options={
                'ordering': ['email', 'nickname', 'score', 'rating'],
            },
        ),
    ]
