# Generated by Django 4.1.5 on 2023-02-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_field', models.ImageField(null=True, upload_to='static/images')),
            ],
        ),
    ]
