# Generated by Django 4.1.5 on 2023-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
