# Generated by Django 4.1.5 on 2023-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pictures_delete_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image_field',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
