# Generated by Django 4.1.5 on 2023-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pictures_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
