# Generated by Django 4.1.5 on 2023-02-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_query_name='mathsiteuser_ptr', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
