# Generated by Django 4.1.5 on 2023-02-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_tests', '0002_testmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='mathsiteuser_ptr', to=settings.AUTH_USER_MODEL),
        ),
    ]
