# Generated by Django 4.1.5 on 2023-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_tests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('advanced', 'Advanced'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
